import AdminMenu from "@/components/AdminMenu";
import { Footer } from "@/components/Footer";
import { StaticHeader } from "@/components/Header";
import { getProfile } from "@/services/user";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await getProfile();
  if (!profile) redirect("/");

  return (
    <>
      <StaticHeader profile={profile} />
      <main className="relative w-full h-full grid grid-cols-[49px_1fr] flex-1">
        <AdminMenu />
        <section
          className="w-full h-full pt-6 pb-10 max-w-full mx-auto px-8" // max-w-[1440px]
        >
          <div className="mx-4">{children}</div>
        </section>
      </main>
      <Footer />
    </>
  );
}
